@host = http://localhost:8000/api
# @host =  https://nauristisancins.shuttleapp.rs/api
@routine_id = 89f25d1f-a3e2-4751-a9e8-a173832364a2
@day_id = 41be9411-759c-451e-9d66-85b544313ddb
@exercise_id = d843ec27-bbeb-4620-a0ce-a768faec68ad


# ### health
# GET {{host}}/health HTTP/1.1

# ROUTINES
### create routine
POST {{host}}/v1/routines HTTP/1.1
Content-Type: application/json

{
    "name": "Upper Lower Split",
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl nec ultricies ultricies, nunc nisl aliquam nunc, nec aliquam nisl nisl nec nisl.",
    "is_active": false
}

### update routine
PUT {{host}}/v1/routines HTTP/1.1
Content-Type: application/json

{
    "routine_id": "{{routine_id}}",
    "name": "Death in Venice",
    "description": "Benjamin Britten",
    "is_active": false
}

### get all routines
GET {{host}}/v1/routines HTTP/1.1

### delete routine
# DELETE {{host}}/v1/routines/ca9e548c-3e60-495a-856a-02e3a21a5fe1 HTTP/1.1

# TRAININGDAYS
### create training days
POST {{host}}/v1/training_days HTTP/1.1
Content-Type: application/json

[{
    "day_name": "Push",
    "routine_id": "{{routine_id}}"
}]

### delete training day
DELETE {{host}}/v1/training_days/ac1dd6fc-f565-4283-b19e-c5174e2bb05f HTTP/1.1

### get_training_days by routine_id
GET {{host}}/v1/training_days/{{routine_id}} HTTP/1.1
Content-Type: application/json

### get_training_days_with_exercises by routine_id
GET {{host}}/v1/training_days/with_exercises/{{routine_id}} HTTP/1.1

# EXERCISES
### create exercise
POST {{host}}/v1/exercises/bulk HTTP/1.1
Content-Type: application/json

[
    {
        "exercise_name": "Bench Press",
        "exercise_description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl nec ultricies ultricies, nunc nisl aliquam nunc, nec aliquam nisl nisl nec nisl."
    },
    {
        "exercise_name": "Squat",
        "exercise_description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl nec ultricies ultricies, nunc nisl aliquam nunc, nec aliquam nisl nisl nec nisl."
    },
    {
        "exercise_name": "Deadlift",
        "exercise_description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl nec ultricies ultricies, nunc nisl aliquam nunc, nec aliquam nisl nisl nec nisl."
    },
    {
        "exercise_name": "Pull Up",
        "exercise_description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl nec ultricies ultricies, nunc nisl aliquam nunc, nec aliquam nisl nisl nec nisl."
    },
    {
        "exercise_name": "Dumbbell Row",
        "exercise_description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl nec ultricies ultricies, nunc nisl aliquam nunc, nec aliquam nisl nisl nec nisl."
    },
    {
        "exercise_name": "Dumbbell Press",
        "exercise_description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl nec ultricies ultricies, nunc nisl aliquam nunc, nec aliquam nisl nisl nec nisl."
    },
    {
        "exercise_name": "Dumbbell Curl",
        "exercise_description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl nec ultricies ultricies, nunc nisl aliquam nunc, nec aliquam nisl nisl nec nisl."
    },
    {
        "exercise_name": "Tricep Extension",
        "exercise_description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl nec ultricies ultricies, nunc nisl aliquam nunc, nec aliquam nisl nisl nec nisl."
    },
    {
        "exercise_name": "Leg Press",
        "exercise_description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl nec ultricies ultricies, nunc nisl aliquam nunc, nec aliquam nisl nisl nec nisl."
    },
    {
        "exercise_name": "Leg Curl",
        "exercise_description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl nec ultricies ultricies, nunc nisl aliquam nunc, nec aliquam nisl nisl nec nisl."
    },
    {
        "exercise_name": "Leg Extension",
        "exercise_description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla euismod, nisl nec ultricies ultricies, nunc nisl aliquam nunc, nec aliquam nisl nisl nec nisl."
    }
 ]

### get_exercises
GET {{host}}/v1/exercises HTTP/1.1
Content-Type: application/json

### add exercise to training day
POST {{host}}/v1/exercises/{{exercise_id}}/{{day_id}} HTTP/1.1


### Search exercises by name
GET {{host}}/v1/exercises/search?name=bench%20press
Content-Type: application/json

### get_exercises by day_id
GET {{host}}/v1/exercises/{{day_id}} HTTP/1.1
Content-Type: application/json

### delete exercise from training day
DELETE {{host}}/v1/exercises/38c63a3a-bba1-4f9b-86df-0049cf49f821 HTTP/1.1

### get link table 
GET {{host}}/v1/debug/link_table HTTP/1.1


# SESSIONS
@session_id = 727bbd32-dab4-4e3c-971c-b5b7d23151cb
### create session
POST {{host}}/v1/session/{{day_id}} HTTP/1.1

### get all sessions with exercises by day_id
GET {{host}}/v1/session/{{day_id}} HTTP/1.1

### get all sessions by day_id
GET {{host}}/v1/session/{{day_id}}/all HTTP/1.1

### end session
PUT {{host}}/v1/session/end/{{session_id}} HTTP/1.1